"""PyMuPDF-based rasterization at 150 DPI per page (TZ §13.1).

The rasterizer is the foundation of the visual comparison — every
page is rendered as a PNG so it can be fed into scikit-image's SSIM
and into the diff PNG generator. The module is intentionally tiny:
it only exposes ``rasterize_pdf`` and ``rasterize_page_to_array``,
both of which import PyMuPDF lazily.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from tests.harness._internals import RASTER_DPI

if TYPE_CHECKING:
    import numpy as np


# PyMuPDF ships no type stubs; the documented mypy override for
# ``weasyprint.*`` lives in pyproject.toml. We cannot add the
# ``pymupdf.*`` override ourselves (pyproject.toml is out of scope
# for this shard), so the calls below are annotated with
# ``# type: ignore[no-untyped-call]`` to silence mypy strict mode.


def rasterize_pdf(pdf_path: Path, out_dir: Path) -> list[Path]:
    """Render every page of ``pdf_path`` to PNG at ``RASTER_DPI``.

    Returns the list of generated PNG paths in document order.
    Existing files in ``out_dir`` are preserved (the harness always
    uses a per-fixture directory so this is fine), but the PNGs
    generated by this call are overwritten if they exist.
    """
    import pymupdf  # spike extra, lazy

    out_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    doc = pymupdf.open(pdf_path)  # type: ignore[no-untyped-call]
    try:
        for page_num in range(len(doc)):
            page = doc[page_num]
            pix = page.get_pixmap(dpi=RASTER_DPI)
            out_path = out_dir / f"page-{page_num + 1}.png"
            pix.save(out_path)  # type: ignore[no-untyped-call]
            paths.append(out_path)
    finally:
        doc.close()  # type: ignore[no-untyped-call]
    return paths


def rasterize_page_to_array(pdf_path: Path, page_index: int) -> np.ndarray:
    """Render a single page to an RGB ``uint8`` numpy array.

    The array is shaped ``(H, W, 3)``. Alpha channels (if any) are
    dropped — PyMuPDF currently returns 3 channels for the default
    RGB colour space, but the drop is defensive against future
    changes.
    """
    import numpy as np
    import pymupdf  # spike extra, lazy

    doc = pymupdf.open(pdf_path)  # type: ignore[no-untyped-call]
    try:
        page = doc[page_index]
        pix = page.get_pixmap(dpi=RASTER_DPI)
        arr = np.frombuffer(pix.samples, dtype=np.uint8).reshape(pix.height, pix.width, pix.n)
        if arr.shape[2] == 4:
            arr = arr[:, :, :3]
        return arr
    finally:
        doc.close()  # type: ignore[no-untyped-call]


def page_pixel_size(pdf_path: Path, page_index: int) -> tuple[int, int]:
    """Return ``(width, height)`` in pixels at ``RASTER_DPI``."""
    import pymupdf  # spike extra, lazy

    doc = pymupdf.open(pdf_path)  # type: ignore[no-untyped-call]
    try:
        page = doc[page_index]
        pix = page.get_pixmap(dpi=RASTER_DPI)
        return pix.width, pix.height
    finally:
        doc.close()  # type: ignore[no-untyped-call]
