"""Phase 2 spike fixtures (TZ-PHASE2-BACKEND-SPIKE §T3, §9.1–§9.3).

This package ships 9 logical fixtures × 2 envelopes (weasyprint + typst) = 18
files. Each logical fixture is a self-contained JSON envelope; the pair differs
only in ``template_id`` / ``template_version`` while the data section is
identical, so visual/structural comparison across backends is apples-to-apples.

The 9 logical fixtures are:

* ``waybill-{1,20,75,200,500}`` — MOVE waybill, contract
  ``warehouse.operation-document/v2`` (§9.1).
* ``vehicle-route-sheet-1`` — путевой лист, contract
  ``transport.vehicle-route-sheet/v1`` (§9.2).
* ``fuel-report-{100,500,1500}`` — месячный ГСМ-отчёт, contract
  ``fuel.monthly-report/v1`` (§9.3).

Each fixture pair is generated by ``generate_fixtures.py`` with a fixed seed,
so reruns are byte-identical.
"""
